name: pokedex_flutter
description: Pokedex Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  retrofit: ^4.1.0
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.4.0
  get_it: ^7.2.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.2.0
  palette_generator: ^0.3.2
  shared_preferences: ^2.0.12
  responsive_builder: ^0.7.0
  alice: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  retrofit_generator: ^8.1.0
  build_runner: ^2.1.7
  build_test: ^2.1.5
  json_serializable: ^6.1.3
  freezed: ^2.4.7
  flutter_native_splash: ^2.1.6
  mockito: ^5.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  image: assets/images/splash.png
  color: "#BDD6DD"
  fullscreen: true

